<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>reject实现</title>
  </head>
  <body>
    <script type="text/javascript">
      function myPromise(fn) {
        // 初始化myPromise的状态和值
        this.myPromiseState = 'pedding';
        this.myPromiseValue = undefined;
        // 定义一个变量存放this
        let _this = this;
        // 定义一个变量存放then中的执行函数
        this.thenCallback = undefined;
        // 定义一个变量存放catch中的执行函数
        this.catchCallback = undefined;
        // resolve
        let resolve = function (value) {
          if (_this.myPromiseState === 'pedding') {
            _this.myPromiseState = 'fullfilled';
            _this.myPromiseValue = value;
            if (value instanceof myPromise) {
              value.then(function (res) {
                if (_this.thenCallback) {
                  _this.thenCallback(res);
                }
              });
            } else {
              setTimeout(function () {
                if (_this.thenCallback) {
                  _this.thenCallback(value);
                }
              });
            }
          }
        };
        myPromise.resolve = function (value) {
          return new myPromise((resolve, reject) => {
            resolve(value);
          });
        };
        // reject
        let reject = function (errValue) {
          // errValue = p中的reject执行了
          if (_this.myPromiseState === 'pedding') {
            _this.myPromiseValue = errValue;
            _this.myPromiseState = 'rejected';
            setTimeout(function () {
              if (_this.catchCallback) {
                console.log('---errValue---');
                _this.catchCallback(errValue);
              } else if (_this.thenCallback) {
                _this.thenCallback(errValue);
              } else {
                throw 'catch is not undefined';
              }
            });
          }
        };
        myPromise.reject = function (value) {
          return new myPromise((resolve, reject) => {
            reject(value);
          });
        };
        if (fn) {
          fn(resolve, reject);
        }
      }
      myPromise.prototype.then = function (callback) {
        let _this = this;
        return new myPromise((resolve, reject) => {
          _this.thenCallback = function (value) {
            let state = _this.myPromiseState;
            // 当调用不是catch的时候，信息向下传递，当触发不是rejected的时候继续向下执行
            if (state === 'rejected') {
              reject(value);
            } else {
              let res = callback(value);
              if (
                res instanceof myPromise &&
                res.myPromiseState == 'rejected'
              ) {
                res.catch(function (errValue) {
                  reject(errValue);
                });
              } else {
                resolve(res);
              }
            }
          };
        });
      };
      myPromise.prototype.catch = function (callback) {
        this.catchCallback = function (value) {
          let res = callback(value);
          resolve(res);
        };
      };

      let p = new myPromise((resolve, reject) => {
        resolve('p中的resolve执行了');
        // reject('p中的reject执行了')
      });
      console.log(p);
      p.then((res) => {
        console.log('这是第一个then执行结果');
        console.log(res);
        return 123;
      })
        .then((res) => {
          console.log('这是第二个then执行结果');
          console.log(res);
          return new myPromise((resolve, reject) => {
            resolve('执行resolve结果');
          });
        })
        .then((res) => {
          console.log('这是第三个then执行结果');
          console.log(res);
        })
        .catch((res) => {
          console.log(res);
        });
      // p.catch(err =>{
      //     console.log('catch执行中')
      //     console.log(err)
      // })
    </script>
  </body>
</html>
